version: '3.9'
name: mon-petit-serveur-php
services:
  nginx_default:
    container_name: nginx_default
    image: nginx:1.23.3-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www
    links:
      - php_default
  php_default:
    container_name: php_default
    image: php:8.2-fpm
    working_dir: /var/www
    volumes:
      - ./app:/var/www